# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -X "github.com/version-go/ldflags.buildVersion={{.Version}}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: clonr
    tap:
      owner: oledakotajoe
      name: homebrew-clonr
      branch: main
    url_template: "https://github.com/oledakotajoe/clonr/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: oledakotajoe
      email: stevendakotasheaves@gmail.com

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    description: "A fast and easy to use templating engine."
    license: "MIT"