on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Set Version
        run: node -e "let pkg=require('./package.json'); pkg.version='$RELEASE_VERSION'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
        working-directory: ./.release
      - name: Testing node version
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "ci: test"
          git push origin HEAD:feat/auto_increment_version
