name: release

on:
  push:
    branches: [ feat#2_configurable ]
jobs:
  test-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Generate cmd docs
        run: go build && ./clonr docs -o ./.resources/cmd-docs/

#      - name: copy readme
#        run: cp README.md ./.release/ && cp ./.resources/ ./.release/

      - name: commit results
        run: |
          git config --global user.name 'Steven Sheaves'
          git config --global user.email 'OleDakotaJoe@users.noreply.github.com'
          git commit -m "ci: Updating documentation"
          git push





